### PR TITLE
Dashing playerData

### PR DESCRIPTION
**Pull request by louis-brann**
per Achilles's suggestion:

> Set the byte at internal char data offset +0x670 to 0, at the same time you set the stick params. That byte refers to a frame counter for how long the joystick has been in a cardinal X-axis direction. Byte at 0x671 is the y-axis.

### CODE REVIEW

**Comment by sherman5** [comment]
Why did you remove the "dash dance info"? I'm assuming that was maximum frames you could dash in one direction?

**Comment by louis-brann** [comment]
Um. yeah. good question. I was thinking it was separate from the adding the playerData analog stick info, but I guess it's still useful to have. I'll add that back in

**Comment by sherman5** [comment]
I'm not too concerned with having multiple stuff in one pull request as long as the commit messages are clear

**Comment by sherman5** [comment]
Ok, everything looks good. Anything else you want to add before I merge?

**Comment by louis-brann** [comment]
Not that I can think of at the moment. I'm still not sure exactly how we want to leverage these counters (i.e. when we want to set them to 0 vs. when we don't). Do we want to nail that down before merging?

It may be on a per-move basis than on a controller level. I got dashing to work when setting the X counter to 0 right before calling addMove. Not setting it to 0 results in a walk. So I'm not sure if it can be done in the Controller, but needing it before an individual move is kind of a hassle as well...

**Comment by sherman5** [comment]
I'm going to add the frame counter to the Controller struct and take it into account when writing. The variables will still be exposed with what you did here, and that way devs can modify the values directly if they choose

**Comment by louis-brann** [comment]
Oh ok, sounds good 👍

**Pull request merged**
